/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { Group } from "three";
import { useFrame } from "@react-three/fiber";

export default function Patient() {
  const group = useRef<Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "/assets/models/patient.gltf"
  ) as any;
  const { actions } = useAnimations(animations, group);

  return (
    <group ref={group} dispose={null}>
      <group
        name="Armature"
        position={[0, -27.5, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.02}
      >
        <primitive object={nodes.mixamorigHips} frustumCulled={false} />
        <skinnedMesh
          geometry={nodes.Circle037.geometry}
          material={materials["skinM.005"]}
          skeleton={nodes.Circle037.skeleton}
          frustumCulled={false}
        />
        <skinnedMesh
          geometry={nodes.Circle041.geometry}
          material={materials["pant.004"]}
          skeleton={nodes.Circle041.skeleton}
          frustumCulled={false}
        />
        <skinnedMesh
          geometry={nodes.Circle078.geometry}
          material={materials["Hat.001"]}
          skeleton={nodes.Circle078.skeleton}
          frustumCulled={false}
        />
        <skinnedMesh
          geometry={nodes.Cube008.geometry}
          material={materials.shirt}
          skeleton={nodes.Cube008.skeleton}
          frustumCulled={false}
        />
        <skinnedMesh
          geometry={nodes.Cube015.geometry}
          material={nodes.Cube015.material}
          skeleton={nodes.Cube015.skeleton}
          frustumCulled={false}
        />
        <skinnedMesh
          geometry={nodes.Cube016.geometry}
          material={nodes.Cube016.material}
          skeleton={nodes.Cube016.skeleton}
          frustumCulled={false}
        />
        <skinnedMesh
          geometry={nodes.Cube017.geometry}
          material={nodes.Cube017.material}
          skeleton={nodes.Cube017.skeleton}
          frustumCulled={false}
        />
        <skinnedMesh
          geometry={nodes.Cylinder015.geometry}
          material={nodes.Cylinder015.material}
          skeleton={nodes.Cylinder015.skeleton}
          frustumCulled={false}
        />
        <skinnedMesh
          geometry={nodes.Cylinder016.geometry}
          material={nodes.Cylinder016.material}
          skeleton={nodes.Cylinder016.skeleton}
          frustumCulled={false}
        />
        <skinnedMesh
          geometry={nodes.Icosphere001.geometry}
          material={nodes.Icosphere001.material}
          skeleton={nodes.Icosphere001.skeleton}
          frustumCulled={false}
        />
        <skinnedMesh
          geometry={nodes.Plane004.geometry}
          material={nodes.Plane004.material}
          skeleton={nodes.Plane004.skeleton}
          frustumCulled={false}
        />
        <skinnedMesh
          geometry={nodes.Plane005.geometry}
          material={nodes.Plane005.material}
          skeleton={nodes.Plane005.skeleton}
          frustumCulled={false}
        />
        <skinnedMesh
          geometry={nodes.Plane006.geometry}
          material={nodes.Plane006.material}
          skeleton={nodes.Plane006.skeleton}
          frustumCulled={false}
        />
      </group>
    </group>
  );
}
