/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useBox, useSphere } from "@react-three/cannon";
import { useFrame } from "@react-three/fiber";

const vec = new THREE.Vector3();

export default function Programming_2D({ ...props }) {
  const { nodes, materials } = useGLTF("/assets/models/Programming_2D.gltf");

  const position = useRef([0, 0, 0]);

  useEffect(() => api.position.subscribe((v) => (position.current = v)), [api]);
  useFrame(() => {
    if (props?.selected && !props?.isMobile) {
      api.applyForce(
        vec
          .set(
            ...[
              position.current[0] - 6,
              position.current[1] - 1,
              position.current[2],
            ]
          )
          .normalize()
          .multiplyScalar(-1)
          .multiplyScalar(7)
          .toArray(),
        [0, 0, 0]
      );
    } else {
      api.applyForce(
        vec
          .set(
            ...[
              position.current[0],
              position.current[1] + (props?.selected ? 7 : 0),
              position.current[2],
            ]
          )
          .normalize()
          .multiplyScalar(-1)
          .multiplyScalar(7)
          .toArray(),
        [0, 0, 0]
      );
    }
  });

  const [ref, api] = useBox(() => ({ mass: 1.25, args: [3.2, 2.4, 1.25] }));

  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Programming.geometry}
        material={nodes.Programming.material}
        material-color={"#6648E9"}
        scale={[1, 1, 0.11]}
      />
    </group>
  );
}
