import Intro from "@components/TopBanner/Intro";
import Title from "@components/TopBanner/Title";
import type { NextPage } from "next";
import {
  makeUseVisualState,
  motion,
  useElementScroll,
  useMotionValue,
  useViewportScroll,
} from "framer-motion";
import Head from "next/head";
import { Suspense, useEffect, useState } from "react";
import dynamic from "next/dynamic";
import useWindowSize from "@components/hooks/useWindowSize";
const Hero = dynamic(() => {
  return import("../components/r3f/Hero");
});

const Home: NextPage = () => {
  const [finishedLoading, setLoadingStatus] = useState<boolean>(false);
  const [introComplete, setIntroComplete] = useState<boolean>(false);
  const [isContinued, setContinued] = useState<boolean>(false);
  // Window Size
  const [width, height] = useWindowSize();
  // Framer Motion
  const mouseX = useMotionValue(0);
  const mouseY = useMotionValue(0);
  const { scrollY } = useViewportScroll();

  const handleLoadComplete = (e: Event) => {
    setLoadingStatus(true);
  };

  return (
    <motion.div
      className="bg-dark"
      onPointerMove={(e) => {
        mouseX.set(e.clientX / width);
        mouseY.set((e.clientY - scrollY.get()) / height);
      }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Main Canvas */}
      {introComplete && (
        <motion.div
          initial={{
            opacity: 0,
          }}
          animate={{
            opacity: 1,
            transition: {
              delay: 1,
              duration: 2,
            },
          }}
          className="top-0 fixed min-h-screen w-screen grid place-items-center z-10"
        >
          <Hero
            mouseX={mouseX}
            mouseY={mouseY}
            scrollY={scrollY}
            handleLoadComplete={handleLoadComplete}
            isContinued={isContinued}
          />
        </motion.div>
      )}
      <main className="min-h-screen font-eb relative">
        {!(finishedLoading && introComplete) ? (
          <Intro
            handleAnimationComplete={() => {
              setIntroComplete(true);
            }}
          />
        ) : (
          <Title handleContinue={() => setContinued(true)} />
        )}
      </main>
    </motion.div>
  );
};

export default Home;
